### ISSUE TITLE
Date Query Parameters for Holidays

### ISSUE THREAD

**Issue by stanzheng** [floatschedule/api#21]
This is supported in tasks, could `/holidays` also support having query parameters? It would be useful to pull holidays that are in the past. The default now only pulls holidays in the future of the current date.
```
https://api.floatschedule.com/api/v1/holidays?start_date=2014-01-01&end_date=2014-03-21
```

**Comment by lgelfan** [comment]
@stanzheng - you can do this with `start_day` and `end_day` attributes, e.g.
`holidays?start_day=20150101&end_day=20151231`
due to some legacy issues the naming is bit inconsistent, we are working a new version of the API that will standardize all the data. Let us know if you have any additional questions.

**Comment by stanzheng** [comment]
sounds great. Hopefully the new API is also backwards compatible :). Is there a hopeful release date for v2 api? thanks also for weighing in
